**Import Numpy as np**

In [4]:
import numpy as np

**Create an array of 10 zeros**

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array of 10 ones**

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Create an array of 10 fives**

In [7]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Create an array of the integers from 10 to 50**

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Create an array of all the even integers from 10 to 50**

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x3 matrix with values ranging from 0 to 8**

In [17]:
a=np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Create a 3x3 identity matrix**

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use NumPy to generate a random number between 0 and 1**

In [21]:
np.random.rand(1)

array([0.87050326])

**Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution**

In [22]:
np.random.random(25)

array([0.90269565, 0.19973768, 0.59019319, 0.24040208, 0.53886131,
       0.22615671, 0.60065891, 0.58231288, 0.82272806, 0.29617842,
       0.79610432, 0.88592017, 0.99486999, 0.26831243, 0.34136381,
       0.7901676 , 0.3967691 , 0.44649242, 0.70421249, 0.72568746,
       0.45600148, 0.90000938, 0.37816933, 0.25514474, 0.64784259])

**Create an array of 20 linearly spaced points between 0 and 1:**

In [25]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Create an array of 100 linearly spaced points between 0 and 1**

In [26]:
a=np.linspace(0,1,100)
a.reshape(10,10)

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

**Numpy Indexing and Selection**

In [27]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [31]:
mat[3,4]

20

In [33]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [34]:
mat[4]

array([21, 22, 23, 24, 25])

In [36]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Get the sum of all the values in mat**

In [37]:
mat.sum()

325

**Get the mean of the values in mat**

In [38]:
mat.mean()

13.0

**Get the standard deviation of the values in mat**

In [39]:
mat.std()

7.211102550927978

**Get the sum of all the columns in mat**

In [40]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

**Get the sum of all the rows in mat**

In [41]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])